language: go
sudo: false

matrix:
  include:
    - go: 1.5.x
    - go: 1.6.x
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: tip
    - arch: ppc64le
      go: 1.9.x
    - arch: ppc64le
      go: 1.10.x
  allow_failures:
    - go: tip

install:
  - # Skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v ./...
